### ISSUE TITLE
Release failure

### ISSUE THREAD

**Issue by ldez** [traefik/mocktail#16]
```
⨯ release failed after 1m45s               error=1 error occurred:
	* homebrew tap formula: could not update "Formula/mocktail.rb": PUT https://api.github.com/repos/traefik/homebrew-tap/contents/Formula/mocktail.rb: 409 Could not update file: Changes must be made through a pull request. []
```

The constraints on the repo https://github.com/traefik/homebrew-tap should be removed, this repo is only used by automation because the content is generated, no pull request is required in this context.

**Comment by mloiseleur** [comment]
I fixed it this morning.
traefiker has been allowed to push to this repo without PR.
